name: JS Affected Areas

on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install madge
        run: npm install madge
      - name: Install octokit
        run: npm install @octokit/rest@19.0.7
      - name: Check Affected Areas
        uses: actions/github-script@v6
        with:
          script: |
            console.dir(context.repo.owner)
            console.dir(context.repo.repo)
            console.dir(context.payload.pull_request)
            const prValues = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pullNumber: 1,
            };

            const script = require('./src/scripts/generateModifiedAreasReport.js')
            script(prValues)

      - name: Save results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: modified_files_${{ github.event.pull_request.head.sha }}
          path: ./src/test_results
